revert scapy to version '2.5.0'
To avoid GUI launch failures with error: 
FileNotFoundError: Tcl data directory "C:\Program Files (x86)\GKFlasher\_tcl_data" not found.
[PYI-20332:ERROR] Failed to execute script 'pyi_rth__tkinter' due to unhandled exception!